##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

  #[create-unique-path--]
variables:
  PROJECT_PATH: ${CI_BUILDS_DIR}/llnl-stack-${CI_COMMIT_SHORT_SHA}/care
  PROJECT_PARENT_DIR: ${CI_BUILDS_DIR}/llnl-stack-${CI_COMMIT_SHORT_SHA}
  SPACK_PATH: ${CI_BUILDS_DIR}/llnl-stack-${CI_COMMIT_SHORT_SHA}/spack
  #[--create-unique-path]
  PROJECT_REPO: https://github.com/LLNL/CARE
  PROJECT_REF: develop
  SPACK_REPO: https://github.com/spack/spack.git
  SPACK_REF: 1c92d832b6eefaf2cf1d053ff621ddd44de7606e
  SPACK_DEBUG: "-d"
  ENV_NAME: "care"

# We only do one generation per stage because we found conflicts otherwise
#[one-generate-per-stage--]
stages:
  - get-repos
#  - generate-quartz
  - generate-lassen
  - build
  - rm-repos
#[--one-generate-per-stage]

.on-quartz:
  tags: [shell, quartz]

.on-lassen:
  tags: [shell, lassen]

#[get-repos--]
get-repos:
  extends: [.on-quartz]
  stage: get-repos
  script:
    - export SPACK_PACKAGE_DIR=$SPACK_PATH/var/spack/repos/builtin/packages
    - export CARE_PACKAGE_DIR=$CARE_PATH/scripts/spack_packages
    - scripts/get-spack
    - scripts/get-care
    - scripts/copy-care-packages
#[--get-repos]

#[rm-repos--]
rm-repos:
  extends: [.on-quartz]
  stage: rm-repos
  script:
    - scripts/remove-repos
#[--rm-repos]

include:
  - .gitlab/generate.yml
